# Generated by Django 4.2.20 on 2025-04-07 18:04

from django.db import migrations


def set_prices_to_products(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')

    for item in OrderItem.objects.all():
        product = Product.objects.get(id=item.product_id)
        item.price = product.price
        item.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_prices_to_products)
    ]
