# Generated by Django 4.2.20 on 2025-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250407_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROC', 'Обработанный'), ('UNPR', 'Необработанный')], default='UNPR', max_length=4),
        ),
    ]
