# Generated by Django 4.2.20 on 2025-04-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_now',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.restaurant', verbose_name='Готовит сейчас'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROC', 'Обработанный'), ('UNPR', 'Необработанный'), ('COOK', 'Готовится')], default='UNPR', max_length=4, verbose_name='статус'),
        ),
    ]
