# Generated by Django 3.2.15 on 2025-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20250405_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, through='foodcartapp.OrderItem', to='foodcartapp.Product', verbose_name='Содержание заказа'),
        ),
    ]
