# Generated by Django 4.2.20 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адресс')),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Широта')),
            ],
        ),
    ]
